FROM node:24-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci --no-audit --fetch-retries=5
COPY . .
CMD ["sh", "-c", "npx prisma generate && npm run start:dev"]
